const EXTERNAL_URL_RE = /^(?:[a-z][a-z0-9+.-]*:|\/\/)/i
const DATA_OR_BLOB_URL_RE = /^(?:data|blob):/i

/**
 * Characters that end a URL in the contexts built output embeds it in:
 * JS string literals, CSS url(), and HTML attributes.
 * ';' is deliberately absent so an HTML-escaped '&amp;' separator is not truncated.
 * '(' and ')' are deliberately absent: they can appear inside a pre-existing query,
 * and the component-boundary check below already handles them.
 */
const URL_END_RE = /["'`\s<>#]/

/**
 * Characters that can appear inside a query component generated by buildQuery.
 * buildQuery percent-encodes everything else, so any other character marks the
 * end of the component.
 */
const QUERY_VALUE_CHAR_RE = /[A-Za-z0-9._%=-]/

/** Whether `index` is at or past the end of a query component */
function isComponentEnd(text: string, index: number): boolean {
  const char = text[index]
  return char === undefined || !QUERY_VALUE_CHAR_RE.test(char)
}

/** Inserts a query before any hash fragment, choosing '&' when the URL already has one */
function insertQuery(url: string, query: string): string {
  const hashIndex = url.indexOf('#')
  const pathname = hashIndex === -1 ? url : url.slice(0, hashIndex)
  const hash = hashIndex === -1 ? '' : url.slice(hashIndex)
  const separator = pathname.includes('?') ? '&' : '?'

  return `${pathname}${separator}${query}${hash}`
}

/**
 * Appends a query string to a URL.
 * External URLs, data:, and blob: are excluded. Inserted before any hash fragment.
 */
export function appendQuery(url: string, query: string): string {
  if (query === '' || EXTERNAL_URL_RE.test(url)) return url
  return insertQuery(url, query)
}

/**
 * Appends a query to a URL pointing at an asset emitted by this plugin.
 * Unlike appendQuery, http/https and protocol-relative URLs are also included (for a CDN base).
 * Only data: and blob: are excluded. Inserted before any hash fragment.
 */
export function appendQueryToBuiltUrl(url: string, query: string): string {
  if (query === '' || DATA_OR_BLOB_URL_RE.test(url)) return url
  return insertQuery(url, query)
}

const EXTRA_ENCODE_RE = /[!~*'()]/g

/**
 * Percent-encodes a query component.
 * encodeURIComponent leaves !~*'() unescaped. Encoding them too keeps the generated
 * query within the QUERY_VALUE_CHAR_RE set that hasQueryParam and countQueryParams rely on.
 */
function encodeQueryComponent(value: string): string {
  return encodeURIComponent(value).replace(
    EXTRA_ENCODE_RE,
    (char) => `%${char.codePointAt(0)?.toString(16).toUpperCase()}`,
  )
}

/** Builds the query string from key and version */
export function buildQuery(key: string | false, version: string): string {
  const encodedVersion = encodeQueryComponent(version)
  return key === false ? encodedVersion : `${encodeQueryComponent(key)}=${encodedVersion}`
}

/**
 * Whether the query string starting at `index` carries `query` as a complete parameter.
 * `index` must point at the character right after the pathname.
 * Both separators are accepted, since insertQuery joins with '&' when the URL already has a query.
 */
export function hasQueryParam(text: string, index: number, query: string): boolean {
  if (query === '') return false
  if (text[index] !== '?') return false

  let end = index + 1
  while (end < text.length && !URL_END_RE.test(text[end] ?? '')) end += 1

  let start = index + 1
  while (start < end) {
    if (text.startsWith(query, start) && isComponentEnd(text, start + query.length)) return true

    const ampIndex = text.indexOf('&', start)
    if (ampIndex === -1 || ampIndex >= end) return false

    start = text.startsWith('&amp;', ampIndex) ? ampIndex + 5 : ampIndex + 1
  }

  return false
}

/** Counts how many times `query` appears as a complete URL query parameter in `text` */
export function countQueryParams(text: string, query: string): number {
  if (query === '') return 0

  let count = 0
  let index = text.indexOf(query)

  while (index !== -1) {
    const afterSeparator =
      text[index - 1] === '?' || text[index - 1] === '&' || text.endsWith('&amp;', index)

    if (afterSeparator && isComponentEnd(text, index + query.length)) {
      count += 1
    }
    index = text.indexOf(query, index + 1)
  }

  return count
}

/** Joins base and an output filename (equivalent to Vite's internal joinUrlSegments) */
export function joinUrlSegments(base: string, path: string): string {
  if (base === '' || path === '') return base + path

  const trimmedBase = base.endsWith('/') ? base.slice(0, -1) : base
  const prefixedPath = path.startsWith('/') ? path : `/${path}`

  return trimmedBase + prefixedPath
}
